# Generated by Django 6.0.6 on 2026-06-08 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 15, 20, 1, 27, 73296, tzinfo=datetime.timezone.utc)),
        ),
    ]
